pipeline {
    agent any

    environment {
        AWS_REGION   = 'eu-north-1'
        AWS_ACCOUNT  = '135234114190'
        ECR_REGISTRY = '135234114190.dkr.ecr.eu-north-1.amazonaws.com'
        ECR_REPO     = 'python-devsecops-app'
        IMAGE_NAME   = 'python-devsecops-app'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Dependency Scan - pip-audit') {
            steps {
                sh '''
                docker run --rm \
                  -v $(pwd):/src \
                  -w /src \
                  python:3.12-slim \
                  sh -c "pip install --no-cache-dir pip-audit && pip-audit -r requirements.txt --progress-spinner off || true"
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Container Scan - Trivy') {
            steps {
                sh '''
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  aquasec/trivy image \
                  --severity HIGH,CRITICAL \
                  --no-progress \
                  $IMAGE_NAME:latest || true
                '''
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([
                    string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ECR_REGISTRY
                    '''
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh '''
                docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$ECR_REPO:latest
                docker push $ECR_REGISTRY/$ECR_REPO:latest
                '''
            }
        }
    }
}
